import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLang = new BehaviorSubject<string>('en');
  lang$ = this.currentLang.asObservable();

  private translations: any = {
    en: {
      // Sidebar
      taskFeed: 'Task Feed',
      myTasks: 'My Tasks',
      helpOffers: 'Help Offers',
      myAppliedTasks: 'My Applied Tasks',
      postTask: '+ Post a Task',
      myProfile: 'My Profile',
      settings: 'Settings',
      logout: 'Logout',
      welcomeBack: 'Welcome back,',

      // Feed
      feedTitle: 'Task Feed',
      feedSubtitle: 'Discover tasks created by others and offer your help!',
      requestToHelp: 'Request to Help',
      posted: 'Posted',
      noTasksAvailable: 'No tasks available',
      noTasksDesc: 'There are currently no open tasks from other users. Check back later!',
      loadingTasks: 'Loading tasks...',

      // My Tasks
      myTasksTitle: 'My Tasks',
      myTasksSubtitle: 'Tasks you have posted',
      edit: 'Edit',
      delete: 'Delete',
      save: 'Save',
      cancel: 'Cancel',
      confirmDelete: 'Are you sure you want to delete this task?',
      noMyTasks: 'No tasks yet',
      noMyTasksDesc: 'You haven\'t posted any tasks yet. Click "Post a Task" to get started!',

      // Help Offers
      helpOffersTitle: 'Help Offers',
      helpOffersSubtitle: 'People who want to help with your tasks',
      accept: 'Accept',
      reject: 'Reject',
      noHelpOffers: 'No help offers',
      noHelpOffersDesc: 'When someone offers to help with your tasks, they\'ll appear here.',
      forTask: 'For task:',
      requested: 'Requested',

      // My Applied Tasks
      appliedTitle: 'My Applied Tasks',
      appliedSubtitle: 'Tasks you have volunteered to help with',
      noApplied: 'No applied tasks yet',
      noAppliedDesc: 'When you offer to help with someone\'s task, it will appear here.',
      waitingResponse: 'Waiting for the task owner to respond...',
      requestAccepted: 'Your request was accepted!',
      requestDeclined: 'Your request was declined.',
      youApplied: 'You applied',
      taskPosted: 'Task posted',
      withdraw: 'Withdraw',

      // Post Task
      postTaskTitle: 'Post a New Task',
      postTaskSubtitle: 'Describe what you need help with and find nearby helpers!',
      taskTitle: 'Task Title',
      description: 'Description',
      location: 'Location',
      startTime: 'Start Time',
      endTime: 'End Time',
      imageUrl: 'Image URL',
      optional: 'optional',
      postTaskBtn: 'Post Task',
      creating: 'Creating...',
      titleRequired: 'Title is required.',

      // Settings
      appSettings: 'Application Settings',
      settingsSubtitle: 'Customize your experience, notifications, and preferences.',
      notifications: 'Notifications',
      emailNotif: 'Email Notifications',
      emailNotifDesc: 'Receive updates about your tasks via email',
      pushNotif: 'Push Notifications',
      pushNotifDesc: 'Get real-time alerts in your browser',
      taskAlerts: 'Task Alerts',
      taskAlertsDesc: 'Get notified when someone requests to help you',
      appearance: 'Appearance & Preferences',
      darkMode: 'Dark Mode',
      darkModeDesc: 'Switch to a dark theme for easier nighttime viewing',
      language: 'Language',
      languageDesc: 'Select your preferred language',
      saveSettings: 'Save Settings',
      settingsSaved: 'Settings saved',

      // Profile
      profileTitle: 'My Profile',
      profileSubtitle: 'Manage your profile details and professional preferences.',
      editProfile: 'Edit Profile',
      cancelEdit: 'Cancel Edit',
      firstName: 'First Name',
      lastName: 'Last Name',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      changePassword: 'Change Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      passwordMismatch: 'Passwords do not match.',
      passwordHint: 'Leave blank if you don\'t want to change your current password.',
      saveProfileChanges: 'Save Profile Changes',
      professionalDetails: 'Professional Details',
      skills: 'Skills / Services Offered',
      hourlyRate: 'Hourly Rate',
      availability: 'Availability Status',
      portfolio: 'Portfolio / Website URL',
      availableForWork: 'Available for work',
      notLookingButOpen: 'Not looking but open',
      notAvailable: 'Not available'
    },
    hi: {
      taskFeed: 'टास्क फीड',
      myTasks: 'मेरे कार्य',
      helpOffers: 'सहायता प्रस्ताव',
      myAppliedTasks: 'मेरे आवेदित कार्य',
      postTask: '+ कार्य पोस्ट करें',
      myProfile: 'मेरी प्रोफ़ाइल',
      settings: 'सेटिंग्स',
      logout: 'लॉग आउट',
      welcomeBack: 'वापसी पर स्वागत है,',
      feedTitle: 'टास्क फीड',
      feedSubtitle: 'दूसरों द्वारा बनाए गए कार्यों को खोजें और अपनी सहायता प्रदान करें!',
      requestToHelp: 'सहायता का अनुरोध',
      posted: 'पोस्ट किया',
      noTasksAvailable: 'कोई कार्य उपलब्ध नहीं',
      noTasksDesc: 'वर्तमान में अन्य उपयोगकर्ताओं से कोई खुले कार्य नहीं हैं।',
      loadingTasks: 'कार्य लोड हो रहे हैं...',
      myTasksTitle: 'मेरे कार्य',
      myTasksSubtitle: 'आपके द्वारा पोस्ट किए गए कार्य',
      edit: 'संपादित करें',
      delete: 'हटाएं',
      save: 'सहेजें',
      cancel: 'रद्द करें',
      confirmDelete: 'क्या आप वाकई इस कार्य को हटाना चाहते हैं?',
      noMyTasks: 'अभी तक कोई कार्य नहीं',
      noMyTasksDesc: 'आपने अभी तक कोई कार्य पोस्ट नहीं किया है।',
      helpOffersTitle: 'सहायता प्रस्ताव',
      helpOffersSubtitle: 'जो लोग आपके कार्यों में मदद करना चाहते हैं',
      accept: 'स्वीकार करें',
      reject: 'अस्वीकार करें',
      noHelpOffers: 'कोई सहायता प्रस्ताव नहीं',
      noHelpOffersDesc: 'जब कोई आपके कार्यों में मदद करेगा, तो वे यहां दिखाई देंगे।',
      forTask: 'कार्य के लिए:',
      requested: 'अनुरोध किया',
      appliedTitle: 'मेरे आवेदित कार्य',
      appliedSubtitle: 'जिन कार्यों में आपने मदद करने के लिए स्वयंसेवा की है',
      noApplied: 'अभी तक कोई आवेदित कार्य नहीं',
      noAppliedDesc: 'जब आप किसी के कार्य में मदद करेंगे, तो वह यहां दिखाई देगा।',
      waitingResponse: 'कार्य स्वामी की प्रतिक्रिया की प्रतीक्षा...',
      requestAccepted: 'आपका अनुरोध स्वीकार किया गया!',
      requestDeclined: 'आपका अनुरोध अस्वीकार किया गया।',
      youApplied: 'आपने आवेदन किया',
      taskPosted: 'कार्य पोस्ट किया',
      withdraw: 'वापस लें',
      postTaskTitle: 'नया कार्य पोस्ट करें',
      postTaskSubtitle: 'बताएं कि आपको किसमें मदद चाहिए!',
      taskTitle: 'कार्य शीर्षक',
      description: 'विवरण',
      location: 'स्थान',
      startTime: 'शुरू का समय',
      endTime: 'समाप्ति का समय',
      imageUrl: 'छवि URL',
      optional: 'वैकल्पिक',
      postTaskBtn: 'कार्य पोस्ट करें',
      creating: 'बना रहा है...',
      titleRequired: 'शीर्षक आवश्यक है।',
      appSettings: 'सेटिंग्स',
      settingsSubtitle: 'अपने अनुभव और प्राथमिकताएं अनुकूलित करें।',
      notifications: 'सूचनाएं',
      emailNotif: 'ईमेल सूचनाएं',
      emailNotifDesc: 'ईमेल द्वारा अपडेट प्राप्त करें',
      pushNotif: 'पुश सूचनाएं',
      pushNotifDesc: 'ब्राउज़र में रीयल-टाइम अलर्ट',
      taskAlerts: 'कार्य अलर्ट',
      taskAlertsDesc: 'सहायता अनुरोध पर सूचित हों',
      appearance: 'दिखावट और प्राथमिकताएं',
      darkMode: 'डार्क मोड',
      darkModeDesc: 'रात के लिए डार्क थीम',
      language: 'भाषा',
      languageDesc: 'अपनी पसंदीदा भाषा चुनें',
      saveSettings: 'सेटिंग्स सहेजें',
      settingsSaved: 'सेटिंग्स सहेजी गईं',
      profileTitle: 'मेरी प्रोफ़ाइल',
      profileSubtitle: 'अपनी प्रोफ़ाइल विवरण प्रबंधित करें।',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      cancelEdit: 'संपादन रद्द करें',
      firstName: 'पहला नाम',
      lastName: 'अंतिम नाम',
      emailAddress: 'ईमेल पता',
      phoneNumber: 'फ़ोन नंबर',
      changePassword: 'पासवर्ड बदलें',
      newPassword: 'नया पासवर्ड',
      confirmPassword: 'पासवर्ड की पुष्टि',
      passwordMismatch: 'पासवर्ड मेल नहीं खाते।',
      passwordHint: 'अगर आप अपना पासवर्ड नहीं बदलना चाहते तो खाली छोड़ दें।',
      saveProfileChanges: 'प्रोफ़ाइल परिवर्तन सहेजें',
      professionalDetails: 'व्यावसायिक विवरण',
      skills: 'कौशल / सेवाएं',
      hourlyRate: 'प्रति घंटा दर',
      availability: 'उपलब्धता स्थिति',
      portfolio: 'पोर्टफ़ोलियो URL',
      availableForWork: 'काम के लिए उपलब्ध',
      notLookingButOpen: 'ढूंढ नहीं रहे पर तैयार',
      notAvailable: 'उपलब्ध नहीं'
    },
    kn: {
      taskFeed: 'ಕಾರ್ಯ ಫೀಡ್',
      myTasks: 'ನನ್ನ ಕಾರ್ಯಗಳು',
      helpOffers: 'ಸಹಾಯ ಪ್ರಸ್ತಾಪಗಳು',
      myAppliedTasks: 'ನನ್ನ ಅರ್ಜಿ ಕಾರ್ಯಗಳು',
      postTask: '+ ಕಾರ್ಯ ಪೋಸ್ಟ್ ಮಾಡಿ',
      myProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      logout: 'ಲಾಗ್ ಔಟ್',
      welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ,',
      feedTitle: 'ಕಾರ್ಯ ಫೀಡ್',
      feedSubtitle: 'ಇತರರ ಕಾರ್ಯಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ನಿಮ್ಮ ಸಹಾಯ ನೀಡಿ!',
      requestToHelp: 'ಸಹಾಯ ವಿನಂತಿ',
      posted: 'ಪೋಸ್ಟ್ ಮಾಡಲಾಗಿದೆ',
      noTasksAvailable: 'ಯಾವುದೇ ಕಾರ್ಯಗಳಿಲ್ಲ',
      noTasksDesc: 'ಪ್ರಸ್ತುತ ಇತರ ಬಳಕೆದಾರರಿಂದ ಯಾವುದೇ ಕಾರ್ಯಗಳಿಲ್ಲ.',
      loadingTasks: 'ಕಾರ್ಯಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
      myTasksTitle: 'ನನ್ನ ಕಾರ್ಯಗಳು',
      myTasksSubtitle: 'ನೀವು ಪೋಸ್ಟ್ ಮಾಡಿದ ಕಾರ್ಯಗಳು',
      edit: 'ಸಂಪಾದಿಸಿ',
      delete: 'ಅಳಿಸಿ',
      save: 'ಉಳಿಸಿ',
      cancel: 'ರದ್ದುಮಾಡಿ',
      confirmDelete: 'ನೀವು ಈ ಕಾರ್ಯವನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?',
      noMyTasks: 'ಇನ್ನೂ ಯಾವುದೇ ಕಾರ್ಯಗಳಿಲ್ಲ',
      noMyTasksDesc: 'ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಕಾರ್ಯಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿಲ್ಲ.',
      helpOffersTitle: 'ಸಹಾಯ ಪ್ರಸ್ತಾಪಗಳು',
      helpOffersSubtitle: 'ನಿಮ್ಮ ಕಾರ್ಯಗಳಲ್ಲಿ ಸಹಾಯ ಮಾಡಲು ಬಯಸುವ ಜನರು',
      accept: 'ಸ್ವೀಕರಿಸಿ',
      reject: 'ತಿರಸ್ಕರಿಸಿ',
      noHelpOffers: 'ಯಾವುದೇ ಸಹಾಯ ಪ್ರಸ್ತಾಪಗಳಿಲ್ಲ',
      noHelpOffersDesc: 'ಯಾರಾದರೂ ನಿಮ್ಮ ಕಾರ್ಯಗಳಲ್ಲಿ ಸಹಾಯ ಮಾಡಿದಾಗ ಅವರು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತಾರೆ.',
      forTask: 'ಕಾರ್ಯಕ್ಕಾಗಿ:',
      requested: 'ವಿನಂತಿಸಲಾಗಿದೆ',
      appliedTitle: 'ನನ್ನ ಅರ್ಜಿ ಕಾರ್ಯಗಳು',
      appliedSubtitle: 'ನೀವು ಸಹಾಯ ಮಾಡಲು ಸ್ವಯಂಸೇವೆ ಮಾಡಿದ ಕಾರ್ಯಗಳು',
      noApplied: 'ಇನ್ನೂ ಯಾವುದೇ ಅರ್ಜಿ ಕಾರ್ಯಗಳಿಲ್ಲ',
      noAppliedDesc: 'ನೀವು ಯಾರೊಬ್ಬರ ಕಾರ್ಯದಲ್ಲಿ ಸಹಾಯ ಮಾಡಿದಾಗ ಅದು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ.',
      waitingResponse: 'ಕಾರ್ಯ ಮಾಲೀಕರ ಪ್ರತಿಕ್ರಿಯೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ...',
      requestAccepted: 'ನಿಮ್ಮ ವಿನಂತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ!',
      requestDeclined: 'ನಿಮ್ಮ ವಿನಂತಿ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ.',
      youApplied: 'ನೀವು ಅರ್ಜಿ ಹಾಕಿದ್ದೀರಿ',
      taskPosted: 'ಕಾರ್ಯ ಪೋಸ್ಟ್ ಮಾಡಲಾಗಿದೆ',
      withdraw: 'ಹಿಂಪಡೆಯಿರಿ',
      postTaskTitle: 'ಹೊಸ ಕಾರ್ಯ ಪೋಸ್ಟ್ ಮಾಡಿ',
      postTaskSubtitle: 'ನಿಮಗೆ ಯಾವ ಸಹಾಯ ಬೇಕು ಎಂದು ವಿವರಿಸಿ!',
      taskTitle: 'ಕಾರ್ಯ ಶೀರ್ಷಿಕೆ',
      description: 'ವಿವರಣೆ',
      location: 'ಸ್ಥಳ',
      startTime: 'ಪ್ರಾರಂಭ ಸಮಯ',
      endTime: 'ಅಂತಿಮ ಸಮಯ',
      imageUrl: 'ಚಿತ್ರ URL',
      optional: 'ಐಚ್ಛಿಕ',
      postTaskBtn: 'ಕಾರ್ಯ ಪೋಸ್ಟ್ ಮಾಡಿ',
      creating: 'ಸೃಷ್ಟಿಸಲಾಗುತ್ತಿದೆ...',
      titleRequired: 'ಶೀರ್ಷಿಕೆ ಅಗತ್ಯ.',
      appSettings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      settingsSubtitle: 'ನಿಮ್ಮ ಅನುಭವವನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ.',
      notifications: 'ಅಧಿಸೂಚನೆಗಳು',
      emailNotif: 'ಇಮೇಲ್ ಅಧಿಸೂಚನೆಗಳು',
      emailNotifDesc: 'ಇಮೇಲ್ ಮೂಲಕ ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ',
      pushNotif: 'ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು',
      pushNotifDesc: 'ರಿಯಲ್-ಟೈಮ್ ಅಲರ್ಟ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ',
      taskAlerts: 'ಕಾರ್ಯ ಎಚ್ಚರಿಕೆಗಳು',
      taskAlertsDesc: 'ಸಹಾಯ ವಿನಂತಿಯ ಅಧಿಸೂಚನೆ ಪಡೆಯಿರಿ',
      appearance: 'ನೋಟ ಮತ್ತು ಆದ್ಯತೆಗಳು',
      darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
      darkModeDesc: 'ರಾತ್ರಿಗಾಗಿ ಡಾರ್ಕ್ ಥೀಮ್',
      language: 'ಭಾಷೆ',
      languageDesc: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      saveSettings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ',
      settingsSaved: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ',
      profileTitle: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      profileSubtitle: 'ಪ್ರೊಫೈಲ್ ವಿವರಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
      editProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      cancelEdit: 'ಸಂಪಾದನೆ ರದ್ದುಮಾಡಿ',
      firstName: 'ಮೊದಲ ಹೆಸರು',
      lastName: 'ಕೊನೆಯ ಹೆಸರು',
      emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
      phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
      changePassword: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
      newPassword: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
      confirmPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಖಚಿತಪಡಿಸಿ',
      passwordMismatch: 'ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ.',
      passwordHint: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಲು ಬಯಸದಿದ್ದರೆ ಖಾಲಿ ಬಿಡಿ.',
      saveProfileChanges: 'ಪ್ರೊಫೈಲ್ ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
      professionalDetails: 'ವೃತ್ತಿಪರ ವಿವರಗಳು',
      skills: 'ಕೌಶಲ / ಸೇವೆಗಳು',
      hourlyRate: 'ಗಂಟೆಯ ದರ',
      availability: 'ಲಭ್ಯತೆ ಸ್ಥಿತಿ',
      portfolio: 'ಪೋರ್ಟ್‌ಫೋಲಿಯೋ URL',
      availableForWork: 'ಕೆಲಸಕ್ಕೆ ಲಭ್ಯ',
      notLookingButOpen: 'ಹುಡುಕುತ್ತಿಲ್ಲ ಆದರೆ ಸಿದ್ಧ',
      notAvailable: 'ಲಭ್ಯವಿಲ್ಲ'
    }
  };

  constructor() {
    const stored = localStorage.getItem('appSettings');
    if (stored) {
      const s = JSON.parse(stored);
      if (s.language) {
        this.currentLang.next(s.language);
      }
    }
  }

  setLanguage(lang: string) {
    this.currentLang.next(lang);
  }

  getLabels(): any {
    return this.translations[this.currentLang.value] || this.translations['en'];
  }

  t(key: string): string {
    const labels = this.getLabels();
    return labels[key] || (this.translations['en'][key] || key);
  }
}
